### ISSUE TITLE
Larger shows are not downloaded correctly

### ISSUE THREAD

**Issue by privatereese** [citronalco/FM4-7Tage-Download#2]
Larger shows such as "FM4 Most Wanted", are not downloaded correctly as the Downloader tries to download equally named shows in the same file.
A mitigation would be to allow -#no.mp3 for files from the same show that are named equally.

Thanks in advance.

**Comment by citronalco** [comment]
Thanks for letting me know, fixed in https://github.com/citronalco/FM4-7Tage-Download/commit/f6277cd363bdb7a031bf449bbb9add5d717cca91

I simply attached the show's start time to the filename.
FM4 already has shows with multiple parts, like Morning Show. For those the Downloader already adds "[partNo/totalParts]" to the filename (and to the mp3's ID3 tag):

That's what it looks like now:
Morning Show - single show, but due to its length split into multiple parts by FM4:
> FM4 Morning Show 2018-12-17 06_00 [1_5].mp3
> FM4 Morning Show 2018-12-17 06_00 [2_5].mp3
> FM4 Morning Show 2018-12-17 06_00 [3_5].mp3
> FM4 Morning Show 2018-12-17 06_00 [4_5].mp3
> FM4 Morning Show 2018-12-17 06_00 [5_5].mp3

Most Wanted - multiple shows on a single day:
> FM4 Most Wanted 2018-12-15 18_17.mp3
> FM4 Most Wanted 2018-12-15 15_09.mp3
> FM4 Most Wanted 2018-12-15 11_59.mp3

Im Sumpf - one show:
> FM4 Im Sumpf 2018-12-16 21_00.mp3

**Comment by privatereese** [comment]
Thanks a lot for the quick fix. Really appreciate it.
